language: python
addons:
  postgresql: "9.3"
python:
  - "2.7"
before_install:
 - "chmod +x ./install_irods.sh"
 - ./install_irods.sh
 - "chmod +x ./install_pyrods.sh"
 - ./install_pyrods.sh
install: "pip install -r requirements.txt --use-mirrors"
script: "TEST_CONFIG=test.config.MockConfig nosetests test.unittests"
